name: pyrpipe
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - aioeasywebdav=2.4.0=py38h32f6830_1001
  - aiohttp=3.7.3=py38h497a2fe_0
  - alsa-lib=1.2.3=h516909a_0
  - amply=0.1.4=py_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - async-timeout=3.0.1=py_1000
  - attrs=20.3.0=pyhd3deb0d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - bbmap=38.87=h1296035_0
  - bcrypt=3.2.0=py38h1e0a361_1
  - boto3=1.16.47=pyhd8ed1ab_0
  - botocore=1.19.47=pyhd8ed1ab_0
  - brotlipy=0.7.0=py38h8df0ef7_1001
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.17.1=h36c2ea0_0
  - ca-certificates=2020.12.5=ha878542_0
  - cachetools=4.1.1=py_0
  - cairo=1.16.0=hcf35c78_1003
  - certifi=2020.12.5=py38h578d9bd_0
  - cffi=1.14.4=py38ha65f79e_1
  - coincbc=2.10.5=hcee13e7_1
  - colorama=0.4.4=pyhd3eb1b0_0
  - configargparse=1.2.3=pyh9f0ad1d_0
  - cryptography=3.3.1=py38h2b97feb_0
  - curl=7.71.1=he644dc0_8
  - cutadapt=3.1=py38h0213d0e_0
  - datrie=0.8.2=py38h1e0a361_1
  - decorator=4.4.2=py_0
  - dnaio=0.5.0=py38h0213d0e_0
  - docutils=0.16=py38h578d9bd_2
  - dropbox=10.9.0=pyhd3deb0d_0
  - expat=2.2.9=he1b5a44_2
  - fastqc=0.11.9=0
  - fftw=3.3.8=nompi_h8cb7ab2_1114
  - filechunkio=1.8=py_2
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=2.001=hab24e00_0
  - font-ttf-source-code-pro=2.030=hab24e00_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.13.1=h86ecdb6_1001
  - fonts-conda-forge=1=0
  - freetype=2.10.4=he06d7ca_0
  - fribidi=1.0.10=h36c2ea0_0
  - ftputil=4.0.0=py_0
  - gdk-pixbuf=2.42.2=h0c95a7a_2
  - gettext=0.19.8.1=h0b5b191_1005
  - ghostscript=9.18=1
  - giflib=5.2.1=h516909a_2
  - gitdb=4.0.5=py_0
  - gitpython=3.1.11=py_0
  - glib=2.66.4=hcd2ae1e_1
  - google-api-core=1.22.2=py38h32f6830_0
  - google-api-python-client=1.12.8=pyhd3deb0d_0
  - google-auth=1.24.0=pyhd3deb0d_0
  - google-auth-httplib2=0.0.4=pyh9f0ad1d_0
  - google-cloud-core=1.5.0=pyhd3deb0d_0
  - google-cloud-storage=1.19.0=py_0
  - google-crc32c=1.1.0=py38h8838a9a_0
  - google-resumable-media=1.2.0=pyhd3deb0d_0
  - googleapis-common-protos=1.52.0=py38h578d9bd_1
  - graphite2=1.3.14=h23475e2_0
  - graphviz=2.42.3=h0511662_0
  - grpcio=1.34.0=py38hdd6454d_0
  - harfbuzz=2.4.0=h9f30f68_3
  - hdf5=1.10.5=nompi_h5b725eb_1113
  - httplib2=0.18.1=pyh9f0ad1d_0
  - icu=64.2=he1b5a44_1
  - idna=2.10=pyh9f0ad1d_0
  - imagemagick=7.0.10_28=pl5262hfcab4aa_3
  - importlib-metadata=3.3.0=py38h578d9bd_2
  - importlib_metadata=3.3.0=hd8ed1ab_2
  - ipython_genutils=0.2.0=py_1
  - isa-l=2.30.0=h36c2ea0_0
  - jbig=2.1=h516909a_2002
  - jemalloc=5.2.1=he1b5a44_4
  - jinja2=2.11.2=pyh9f0ad1d_0
  - jmespath=0.10.0=pyh9f0ad1d_0
  - jpeg=9d=h516909a_0
  - jsonschema=3.2.0=py_2
  - jupyter_core=4.7.0=py38h578d9bd_0
  - krb5=1.17.2=h926e7f8_0
  - lcms2=2.11=hcbb858e_1
  - ld_impl_linux-64=2.35.1=hed1e6ac_1
  - libblas=3.9.0=6_openblas
  - libcblas=3.9.0=6_openblas
  - libcrc32c=1.1.1=he1b5a44_2
  - libcurl=7.71.1=hcdd3856_8
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.3=he6710b0_2
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=9.3.0=h5dbcf3e_17
  - libgfortran-ng=9.3.0=he4bcb1c_17
  - libgfortran5=9.3.0=he4bcb1c_17
  - libglib=2.66.4=h164308a_1
  - libgomp=9.3.0=h5dbcf3e_17
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=6_openblas
  - libnghttp2=1.41.0=hf8bcb03_2
  - libopenblas=0.3.12=pthreads_h4812303_1
  - libpng=1.6.37=hed695b0_2
  - libprotobuf=3.14.0=h780b84a_0
  - librsvg=2.50.2=h115801e_2
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.9.0=hab1572f_5
  - libstdcxx-ng=9.3.0=h2ae2ef3_17
  - libtiff=4.2.0=hdc55705_0
  - libtool=2.4.6=h58526e2_1007
  - libuuid=2.32.1=h14c3975_1000
  - libwebp=1.1.0=h76fa15c_4
  - libwebp-base=1.1.0=h516909a_3
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=hee79883_0
  - lz4-c=1.9.3=h9c3ff4c_0
  - markupsafe=1.1.1=py38h8df0ef7_2
  - multidict=5.1.0=py38h497a2fe_0
  - nbformat=5.0.8=py_0
  - ncbi-ngs-sdk=2.10.9=h3e72335_0
  - ncurses=6.2=h58526e2_4
  - networkx=2.5=py_0
  - numpy=1.19.4=py38h18fd61f_2
  - oauth2client=4.1.3=py_0
  - openjdk=11.0.8=hacce0ff_0
  - openjpeg=2.4.0=hf7af979_0
  - openssl=1.1.1i=h7f98852_0
  - orfipy=0.0.3=py38hed8969a_0
  - ossuuid=1.6.2=hf484d3e_1000
  - pango=1.42.4=h7062337_4
  - paramiko=2.7.2=pyh9f0ad1d_0
  - pbzip2=1.1.13=0
  - pcre=8.44=he6710b0_0
  - perl=5.26.2=h36c2ea0_1008
  - perl-app-cpanminus=1.7044=pl526_1
  - perl-business-isbn=3.004=pl526_0
  - perl-business-isbn-data=20140910.003=pl526_0
  - perl-carp=1.38=pl526_3
  - perl-constant=1.33=pl526_1
  - perl-data-dumper=2.173=pl526_0
  - perl-encode=2.88=pl526_1
  - perl-exporter=5.72=pl526_1
  - perl-extutils-makemaker=7.36=pl526_1
  - perl-file-path=2.16=pl526_0
  - perl-file-temp=0.2304=pl526_2
  - perl-mime-base64=3.15=pl526_1
  - perl-parent=0.236=pl526_1
  - perl-uri=1.76=pl526_0
  - perl-xml-libxml=2.0132=pl526h7ec2d77_1
  - perl-xml-namespacesupport=1.12=pl526_0
  - perl-xml-sax=1.02=pl526_0
  - perl-xml-sax-base=1.09=pl526_0
  - perl-xsloader=0.24=pl526_0
  - pigz=2.4=h84994c4_0
  - pip=20.3.3=py38h06a4308_0
  - pixman=0.38.0=h516909a_1003
  - pkg-config=0.29.2=h36c2ea0_1008
  - prettytable=2.0.0=pyhd8ed1ab_0
  - protobuf=3.14.0=py38h709712a_0
  - psutil=5.8.0=py38h497a2fe_0
  - pulp=2.3.1=py38h32f6830_0
  - pyahocorasick=1.4.0=py38h1e0a361_2
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pyfastx=0.8.2=py38h197edbe_0
  - pygments=2.7.3=pyhd8ed1ab_0
  - pygraphviz=1.6=py38h25c7686_1
  - pynacl=1.4.0=py38h1e0a361_2
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyrsistent=0.17.3=py38h25fe258_1
  - pysftp=0.2.9=py_1
  - pysocks=1.7.1=py38h924ce5b_2
  - python=3.8.6=hffdb5ce_4_cpython
  - python-dateutil=2.8.1=py_0
  - python-irodsclient=0.8.2=py_0
  - python_abi=3.8=1_cp38
  - pytz=2020.5=pyhd8ed1ab_0
  - ratelimiter=1.2.0=py_1002
  - readline=8.0=he28a2e2_2
  - requests=2.25.1=pyhd3deb0d_0
  - rsa=4.6=pyh9f0ad1d_0
  - s3transfer=0.3.3=pyhd8ed1ab_5
  - salmon=1.4.0=hf69c8f4_0
  - setuptools=51.0.0=py38h06a4308_2
  - simplejson=3.17.2=py38h497a2fe_1
  - six=1.15.0=pyh9f0ad1d_0
  - slacker=0.14.0=py_0
  - smmap=3.0.4=pyh9f0ad1d_0
  - snakemake=5.31.1=0
  - snakemake-minimal=5.31.1=py_0
  - sqlite=3.34.0=h74cdb3f_0
  - sra-tools=2.10.9=pl526haddd2b5_0
  - star=2.7.7a=0
  - stringtie=2.1.4=h7e0af3c_0
  - tbb=2020.3=hfd86e86_0
  - tk=8.6.10=hed695b0_1
  - toposort=1.6=pyhd8ed1ab_0
  - traitlets=5.0.5=py_0
  - trim-galore=0.6.6=0
  - typing-extensions=3.7.4.3=0
  - typing_extensions=3.7.4.3=py_0
  - uritemplate=3.0.1=py_0
  - urllib3=1.26.2=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - wheel=0.36.2=pyhd3eb1b0_0
  - wrapt=1.12.1=py38h25fe258_2
  - xmlrunner=1.7.7=py_0
  - xopen=1.0.1=py38h578d9bd_1
  - xorg-fixesproto=5.0=h14c3975_1002
  - xorg-inputproto=2.3.2=h14c3975_1002
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.12=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxfixes=5.0.3=h516909a_1004
  - xorg-libxi=1.7.10=h516909a_0
  - xorg-libxpm=3.5.13=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-libxt=1.1.5=h516909a_1003
  - xorg-libxtst=1.2.3=h516909a_1002
  - xorg-recordproto=1.14.2=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h27cfd23_1007
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - yarl=1.6.3=py38h497a2fe_0
  - zipp=3.4.0=py_0
  - zlib=1.2.11=h516909a_1010
  - zstd=1.4.8=ha95c52a_1
  - pip:
    - cairocffi==1.2.0
    - cairosvg==2.5.0
    - chardet==4.0.0
    - click==7.1.2
    - coloredlogs==15.0
    - colormath==3.0.0
    - cssselect2==0.4.1
    - cycler==0.10.0
    - defusedxml==0.6.0
    - dill==0.3.3
    - future==0.18.2
    - html5lib==1.1
    - humanfriendly==9.1
    - importlib-resources==4.1.1
    - kiwisolver==1.3.1
    - lzstring==1.0.4
    - markdown==3.3.3
    - matplotlib==3.3.3
    - multiqc==1.9
    - pandas==1.2.0
    - pillow==8.1.0
    - pyphen==0.10.0
    - pyyaml==5.3.1
    - scipy==1.6.0
    - seaborn==0.11.1
    - spectra==0.0.11
    - tinycss2==1.1.0
    - weasyprint==52.2
    - webencodings==0.5.1
